#!/usr/bin/env bash
set -x
(
	cd $(dirname $0)
	etc=./etc
	java_opts=`cat ${etc}/jvm.config`
	java ${java_opts} -cp "./lib/*" \
		-Dlog.levels-file=${etc}/log.properties \
		-Dconfig=${etc}/config.properties \
		com.facebook.presto.server.PrestoServer
)
