#!/usr/bin/env bash
### BEGIN INIT INFO
# Provides:
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

db_prefix="aws://bucketdb-manifests:bucketdb-tables/p"
db_preload_list="taxidata"

# TODO: determine worker count automatically by asking autoscaler
worker_count=1
splits_per_worker=6


# splits_per_worker=2 # 2:03 [398M rows, 6.66GB] [3.24M rows/s, 55.6MB/s]
# splits_per_worker=4 # 1:32 [398M rows, 6.66GB] [4.31M rows/s, 73.9MB/s]
# splits_per_worker=6 # 1:29 [398M rows, 6.66GB] [4.47M rows/s, 76.7MB/s]
# splits_per_worker=8 # 1:29 [398M rows, 6.66GB] [4.44M rows/s, 76.2MB/s]

cmd="NOMS_VERSION_NEXT=1 /var/lib/presto/go/bin/presto-noms-thrift \
--worker-count=${worker_count} \
--splits-per-worker=${splits_per_worker} \
--db-prefix=${db_prefix}
--db-preload-list=${db_preload_list}"

user="presto"

name=`basename $0`
pid_file="/var/run/$name.pid"
stdout_log="/var/log/$name.log"
stderr_log="/var/log/$name.err"

get_pid() {
    cat "$pid_file"
}

is_running() {
    [ -f "$pid_file" ] && ps -p `get_pid` > /dev/null 2>&1
}

case "$1" in
    start)
    if is_running; then
        echo "Already started"
    else
        echo "Starting $name"
        cd "$dir"
        sudo -u "$user" mkdir -p /tmp/presto-noms-cache # temp hack around NewAWSStoreFactory bug requiring table cache
        sudo -u "$user" $cmd >> "$stdout_log" 2>> "$stderr_log" &
        echo $! > "$pid_file"
        if ! is_running; then
            echo "Unable to start, see $stdout_log and $stderr_log"
            exit 1
        fi
    fi
    ;;
    stop)
    if is_running; then
        echo -n "Stopping $name.."
        kill `get_pid`
        for i in 1 2 3 4 5 6 7 8 9 10
        # for i in `seq 10`
        do
            if ! is_running; then
                break
            fi

            echo -n "."
            sleep 1
        done
        echo

        if is_running; then
            echo "Not stopped; may still be shutting down or shutdown may have failed"
            exit 1
        else
            echo "Stopped"
            if [ -f "$pid_file" ]; then
                rm "$pid_file"
            fi
        fi
    else
        echo "Not running"
    fi
    ;;
    restart)
    $0 stop
    if is_running; then
        echo "Unable to stop, will not attempt to start"
        exit 1
    fi
    $0 start
    ;;
    status)
    if is_running; then
        echo "Running"
    else
        echo "Stopped"
        exit 1
    fi
    ;;
    *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
