#!/bin/bash
set -x

app=PrestoApp
group=PrestoDeployment
bucket=bucketdb-builds
bundle=presto-noms-bundle
type=zip
(
    cd $(dirname $0)
    ./bundle
    aws deploy push --application-name ${app} \
      --source $(find target -type d -name ${bundle}-*) \
      --s3-location s3://${bucket}/${bundle}.${type}

    read -p "Deploy now (y/n)? " choice
    case "$choice" in
      y|Y )
        id=$(aws deploy create-deployment \
                --application-name ${app} --deployment-group-name ${group} \
                --s3-location bucket=${bucket},bundleType=${type},key=${bundle}.${type} \
                --output text)
        aws deploy wait deployment-successful --deployment-id ${id}
        ;;
      * )
        echo Deploy later using:
        echo
        echo id=$(aws deploy create-deployment --application-name ${app} --deployment-group-name ${group} --s3-location bucket=${bucket},bundleType=${type},key=${bundle}.${type} --output text)
        echo aws deploy wait deployment-successful --deployment-id '${id}'
        ;;
    esac
)
